namespace NCBRS.Client.App.Pages;

/// <summary>
/// The tablet's icons: Lucide (ISC licence), as 24-unit outline path data
/// drawn with a 2-unit stroke by <see cref="Ui.Icon"/>. Generated by
/// Icons.generate.mjs from the web client's lucide-react package, so the
/// tablet and the web site draw the same symbols; edit that script, not this
/// file. Every path is absolute moves, lines and cubic curves only, because
/// MAUI on Android drew nothing at all for some valid SVG paths.
/// </summary>
public static class Icons
{
    /// <summary>Lucide "house".</summary>
    public const string Home = "M 15 21 L 15 13 C 15 12.448 14.552 12 14 12 L 10 12 C 9.448 12 9 12.448 9 13 L 9 21 M 3 10 C 3 9.411 3.259 8.852 3.709 8.472 L 10.709 2.472 C 11.454 1.842 12.546 1.842 13.291 2.472 L 20.291 8.472 C 20.741 8.852 21 9.411 21 10 L 21 19 C 21 20.105 20.105 21 19 21 L 5 21 C 3.895 21 3 20.105 3 19 Z";

    /// <summary>Lucide "plus".</summary>
    public const string Add = "M 5 12 L 19 12 M 12 5 L 12 19";

    /// <summary>Lucide "list".</summary>
    public const string Records = "M 3 5 L 3.01 5 M 3 12 L 3.01 12 M 3 19 L 3.01 19 M 8 5 L 21 5 M 8 12 L 21 12 M 8 19 L 21 19";

    /// <summary>Lucide "menu".</summary>
    public const string More = "M 4 5 L 20 5 M 4 12 L 20 12 M 4 19 L 20 19";

    /// <summary>Lucide "refresh-cw".</summary>
    public const string Sync = "M 3 12 C 3 7.029 7.029 3 12 3 C 14.516 3.009 16.931 3.991 18.74 5.74 L 21 8 M 21 3 L 21 8 L 16 8 M 21 12 C 21 16.971 16.971 21 12 21 C 9.484 20.991 7.069 20.009 5.26 18.26 L 3 16 M 8 16 L 3 16 L 3 21";

    /// <summary>Lucide "scan-line".</summary>
    public const string ScanLine = "M 3 7 L 3 5 C 3 3.895 3.895 3 5 3 L 7 3 M 17 3 L 19 3 C 20.105 3 21 3.895 21 5 L 21 7 M 21 17 L 21 19 C 21 20.105 20.105 21 19 21 L 17 21 M 7 21 L 5 21 C 3.895 21 3 20.105 3 19 L 3 17 M 7 12 L 17 12";

    /// <summary>Lucide "printer".</summary>
    public const string Print = "M 6 18 L 4 18 C 2.895 18 2 17.105 2 16 L 2 11 C 2 9.895 2.895 9 4 9 L 20 9 C 21.105 9 22 9.895 22 11 L 22 16 C 22 17.105 21.105 18 20 18 L 18 18 M 6 9 L 6 3 C 6 2.448 6.448 2 7 2 L 17 2 C 17.552 2 18 2.448 18 3 L 18 9 M 7 14 L 17 14 C 17.552 14 18 14.448 18 15 L 18 21 C 18 21.552 17.552 22 17 22 L 7 22 C 6.448 22 6 21.552 6 21 L 6 15 C 6 14.448 6.448 14 7 14 Z";

    /// <summary>Lucide "lock".</summary>
    public const string Lock = "M 5 11 L 19 11 C 20.105 11 21 11.895 21 13 L 21 20 C 21 21.105 20.105 22 19 22 L 5 22 C 3.895 22 3 21.105 3 20 L 3 13 C 3 11.895 3.895 11 5 11 Z M 7 11 L 7 7 C 7 4.239 9.239 2 12 2 C 14.761 2 17 4.239 17 7 L 17 11";

    /// <summary>Lucide "download".</summary>
    public const string Export = "M 12 15 L 12 3 M 21 15 L 21 19 C 21 20.105 20.105 21 19 21 L 5 21 C 3.895 21 3 20.105 3 19 L 3 15 M 7 10 L 12 15 L 17 10";

    /// <summary>Lucide "usb".</summary>
    public const string Usb = "M 9 7 C 9 7.552 9.448 8 10 8 C 10.552 8 11 7.552 11 7 C 11 6.448 10.552 6 10 6 C 9.448 6 9 6.448 9 7 Z M 3 20 C 3 20.552 3.448 21 4 21 C 4.552 21 5 20.552 5 20 C 5 19.448 4.552 19 4 19 C 3.448 19 3 19.448 3 20 Z M 4.7 19.3 L 19 5 M 21 3 L 18 4 L 20 6 Z M 9.26 7.68 L 5 12 L 7 17 M 10 14 L 15 16 L 18.5 12.5 M 18 12 L 19 11 L 20 12 L 19 13 Z";

    /// <summary>Lucide "chevron-right".</summary>
    public const string ChevronForward = "M 9 18 L 15 12 L 9 6";

    /// <summary>Lucide "chevron-left".</summary>
    public const string ChevronBack = "M 15 18 L 9 12 L 15 6";

    /// <summary>Lucide "chevron-down".</summary>
    public const string ChevronDown = "M 6 9 L 12 15 L 18 9";

    /// <summary>Lucide "check".</summary>
    public const string Tick = "M 20 6 L 9 17 L 4 12";

    /// <summary>Lucide "x".</summary>
    public const string Close = "M 18 6 L 6 18 M 6 6 L 18 18";

    /// <summary>Lucide "globe".</summary>
    public const string Globe = "M 2 12 C 2 17.523 6.477 22 12 22 C 17.523 22 22 17.523 22 12 C 22 6.477 17.523 2 12 2 C 6.477 2 2 6.477 2 12 Z M 12 2 C 6.667 7.6 6.667 16.4 12 22 C 17.333 16.4 17.333 7.6 12 2 M 2 12 L 22 12";

    /// <summary>Lucide "map-pin".</summary>
    public const string MapPin = "M 20 10 C 20 14.993 14.461 20.193 12.601 21.799 C 12.245 22.067 11.755 22.067 11.399 21.799 C 9.539 20.193 4 14.993 4 10 C 4 5.582 7.582 2 12 2 C 16.418 2 20 5.582 20 10 M 9 10 C 9 11.657 10.343 13 12 13 C 13.657 13 15 11.657 15 10 C 15 8.343 13.657 7 12 7 C 10.343 7 9 8.343 9 10 Z";

    /// <summary>Lucide "cloud-check".</summary>
    public const string CloudCheck = "M 17 15 L 11.5 20.5 L 9 18 M 5.516 16.07 C 2.788 14.503 1.44 11.309 2.221 8.261 C 3.002 5.214 5.72 3.062 8.866 3.001 C 12.012 2.94 14.811 4.985 15.71 8 L 17.5 8 C 19.233 8 20.813 8.996 21.56 10.56 C 22.308 12.124 22.09 13.978 21.001 15.327";

    /// <summary>Lucide "cloud-off".</summary>
    public const string CloudOff = "M 10.94 5.274 C 13.231 5.934 15.029 7.715 15.71 10 L 17.5 10 C 18.972 10 20.35 10.72 21.192 11.927 C 22.033 13.134 22.231 14.676 21.722 16.057 M 18.796 18.81 C 18.376 18.936 17.939 19 17.5 19 L 9 19 C 5.771 18.999 2.961 16.79 2.199 13.652 C 1.437 10.514 2.921 7.261 5.79 5.78 M 2 2 L 22 22";

    /// <summary>Lucide "cloud-upload".</summary>
    public const string CloudUpload = "M 12 13 L 12 21 M 4 14.899 C 1.965 12.82 1.428 9.699 2.652 7.059 C 3.875 4.419 6.604 2.812 9.506 3.021 C 12.408 3.23 14.878 5.212 15.71 8 L 17.5 8 C 19.482 8 21.231 9.297 21.807 11.194 C 22.382 13.091 21.648 15.141 20 16.242 M 8 17 L 12 13 L 16 17";

    /// <summary>Lucide "triangle-alert".</summary>
    public const string Warning = "M 21.73 18 L 13.73 4 C 13.375 3.373 12.71 2.986 11.99 2.986 C 11.27 2.986 10.605 3.373 10.25 4 L 2.25 18 C 1.891 18.622 1.893 19.388 2.254 20.008 C 2.616 20.628 3.282 21.006 4 21 L 20 21 C 20.714 20.999 21.374 20.618 21.731 19.999 C 22.087 19.38 22.087 18.618 21.73 18 M 12 9 L 12 13 M 12 17 L 12.01 17";

    /// <summary>Lucide "circle-alert".</summary>
    public const string Alert = "M 2 12 C 2 17.523 6.477 22 12 22 C 17.523 22 22 17.523 22 12 C 22 6.477 17.523 2 12 2 C 6.477 2 2 6.477 2 12 Z M 12 8 L 12 12 M 12 16 L 12.01 16";

    /// <summary>Lucide "circle-x".</summary>
    public const string Error = "M 2 12 C 2 17.523 6.477 22 12 22 C 17.523 22 22 17.523 22 12 C 22 6.477 17.523 2 12 2 C 6.477 2 2 6.477 2 12 Z M 15 9 L 9 15 M 9 9 L 15 15";

    /// <summary>Lucide "circle-check".</summary>
    public const string Success = "M 2 12 C 2 17.523 6.477 22 12 22 C 17.523 22 22 17.523 22 12 C 22 6.477 17.523 2 12 2 C 6.477 2 2 6.477 2 12 Z M 16 9 L 10.5 14.5 L 8 12";

    /// <summary>Lucide "user".</summary>
    public const string Person = "M 19 21 L 19 19 C 19 16.791 17.209 15 15 15 L 9 15 C 6.791 15 5 16.791 5 19 L 5 21 M 8 7 C 8 9.209 9.791 11 12 11 C 14.209 11 16 9.209 16 7 C 16 4.791 14.209 3 12 3 C 9.791 3 8 4.791 8 7 Z";

    /// <summary>Lucide "user-round-plus".</summary>
    public const string PersonAdd = "M 2 21 C 2 17.855 3.842 15.002 6.709 13.708 C 9.575 12.414 12.934 12.92 15.292 15 M 5 8 C 5 10.761 7.239 13 10 13 C 12.761 13 15 10.761 15 8 C 15 5.239 12.761 3 10 3 C 7.239 3 5 5.239 5 8 Z M 19 16 L 19 22 M 22 19 L 16 19";

    /// <summary>Lucide "delete".</summary>
    public const string Backspace = "M 10 5 C 9.503 5 9.024 5.185 8.656 5.519 L 2.328 11.259 C 2.119 11.449 2 11.717 2 12 C 2 12.282 2.119 12.55 2.328 12.74 L 8.656 18.481 C 9.024 18.815 9.503 19 10 19 L 20 19 C 21.105 19 22 18.105 22 17 L 22 7 C 22 5.895 21.105 5 20 5 Z M 12 9 L 18 15 M 18 9 L 12 15";

    /// <summary>Lucide "shield-plus".</summary>
    public const string Shield = "M 20 13 C 20 18 16.5 20.5 12.34 21.95 C 12.122 22.024 11.886 22.02 11.67 21.94 C 7.5 20.5 4 18 4 13 L 4 6 C 4 5.448 4.448 5 5 5 C 7 5 9.5 3.8 11.24 2.28 C 11.678 1.906 12.322 1.906 12.76 2.28 C 14.51 3.81 17 5 19 5 C 19.552 5 20 5.448 20 6 Z M 9 12 L 15 12 M 12 9 L 12 15";

    /// <summary>Lucide "search".</summary>
    public const string Search = "M 21 21 L 16.66 16.66 M 3 11 C 3 15.418 6.582 19 11 19 C 15.418 19 19 15.418 19 11 C 19 6.582 15.418 3 11 3 C 6.582 3 3 6.582 3 11 Z";

    /// <summary>Lucide "calendar".</summary>
    public const string Calendar = "M 8 2 L 8 5 M 16 2 L 16 5 M 5 3 L 19 3 C 20.105 3 21 3.895 21 5 L 21 19 C 21 20.105 20.105 21 19 21 L 5 21 C 3.895 21 3 20.105 3 19 L 3 5 C 3 3.895 3.895 3 5 3 Z M 3 9 L 21 9";

    /// <summary>Lucide "pencil".</summary>
    public const string Edit = "M 21.174 6.812 C 22.275 5.711 22.275 3.926 21.174 2.826 C 20.074 1.725 18.289 1.724 17.188 2.825 L 3.842 16.174 C 3.61 16.406 3.438 16.691 3.342 17.004 L 2.021 21.356 C 1.968 21.532 2.017 21.723 2.147 21.853 C 2.277 21.983 2.468 22.031 2.644 21.978 L 6.997 20.658 C 7.31 20.563 7.595 20.392 7.827 20.161 Z M 15 5 L 19 9";

    /// <summary>Lucide "file-text".</summary>
    public const string Document = "M 6 22 C 4.895 22 4 21.105 4 20 L 4 4 C 4 2.895 4.895 2 6 2 L 14 2 C 14.639 1.999 15.253 2.253 15.704 2.706 L 19.292 6.294 C 19.746 6.745 20.001 7.36 20 8 L 20 20 C 20 21.105 19.105 22 18 22 Z M 14 2 L 14 7 C 14 7.552 14.448 8 15 8 L 20 8 M 10 9 L 8 9 M 16 13 L 8 13 M 16 17 L 8 17";

    /// <summary>Lucide "hash".</summary>
    public const string Numbers = "M 4 9 L 20 9 M 4 15 L 20 15 M 10 3 L 8 21 M 16 3 L 14 21";

    /// <summary>Lucide "clock".</summary>
    public const string Clock = "M 2 12 C 2 17.523 6.477 22 12 22 C 17.523 22 22 17.523 22 12 C 22 6.477 17.523 2 12 2 C 6.477 2 2 6.477 2 12 Z M 12 6 L 12 12 L 16 14";

    /// <summary>Lucide "key-round".</summary>
    public const string Key = "M 2.586 17.414 C 2.211 17.789 2 18.298 2 18.828 L 2 21 C 2 21.552 2.448 22 3 22 L 6 22 C 6.552 22 7 21.552 7 21 L 7 20 C 7 19.448 7.448 19 8 19 L 9 19 C 9.552 19 10 18.552 10 18 L 10 17 C 10 16.448 10.448 16 11 16 L 11.172 16 C 11.702 16 12.211 15.789 12.586 15.414 L 13.4 14.6 C 16.262 15.597 19.434 14.484 21.044 11.916 C 22.655 9.349 22.278 6.009 20.134 3.866 C 17.991 1.722 14.651 1.345 12.084 2.956 C 9.516 4.566 8.403 7.738 9.4 10.6 Z M 16 7.5 C 16 7.776 16.224 8 16.5 8 C 16.776 8 17 7.776 17 7.5 C 17 7.224 16.776 7 16.5 7 C 16.224 7 16 7.224 16 7.5 Z";

    /// <summary>Lucide "languages".</summary>
    public const string Language = "M 5 8 L 11 14 M 4 14 L 10 8 L 12 5 M 2 5 L 14 5 M 7 2 L 8 2 M 22 22 L 17 12 L 12 22 M 14 18 L 20 18";
}
