using Microsoft.OpenApi;
using NCBRS.Models;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace NCBRS.Middleware;

/// <summary>
/// Advertises the transaction-tracking headers on every operation so they
/// can be filled in from the Swagger UI. They're read by
/// RequestAuditMiddleware before model binding, which is why they travel as
/// headers rather than in a request body -- a GET has no body to put them
/// in, and the middleware runs too early to see one anyway.
/// </summary>
public class TransactionHeaderOperationFilter : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        operation.Parameters ??= [];

        operation.Parameters.Add(new OpenApiParameter
        {
            Name = TransactionContext.TransactionIdHeader,
            In = ParameterLocation.Header,
            Required = false,
            Description = "Caller-supplied transaction id (UUID), echoed back in the response meta. "
                        + "Generated by the server when omitted.",
            Schema = new OpenApiSchema { Type = JsonSchemaType.String, Format = "uuid" }
        });

        operation.Parameters.Add(new OpenApiParameter
        {
            Name = TransactionContext.ClientIdHeader,
            In = ParameterLocation.Header,
            Required = false,
            Description = "Calling application or channel, e.g. \"MobileApp\".",
            Schema = new OpenApiSchema { Type = JsonSchemaType.String }
        });

        WrapResponsesInEnvelope(operation, context);
    }

    /// <summary>
    /// MetaEnvelopeFilter wraps responses at runtime, which Swashbuckle's
    /// schema generation knows nothing about -- so without this the
    /// documented response shape would be the bare payload while the real
    /// one is { meta, data }. Anyone generating a client from this document
    /// would get it wrong.
    /// </summary>
    private static void WrapResponsesInEnvelope(OpenApiOperation operation, OperationFilterContext context)
    {
        var metaSchema = context.SchemaGenerator.GenerateSchema(typeof(ResponseMeta), context.SchemaRepository);

        foreach (var response in operation.Responses.Values)
        {
            if (response.Content is null)
            {
                continue;
            }

            foreach (var media in response.Content.Values)
            {
                media.Schema = new OpenApiSchema
                {
                    Type = JsonSchemaType.Object,
                    Properties = new Dictionary<string, IOpenApiSchema>
                    {
                        ["meta"] = metaSchema,
                        ["data"] = media.Schema ?? new OpenApiSchema()
                    }
                };
            }
        }
    }
}
