using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi;
using NCBRS.Models;

namespace NCBRS.Middleware;

/// <summary>
/// Advertises the transaction-tracking headers on every operation, and
/// describes the response envelope the API actually returns.
///
/// Ported from the Swashbuckle operation filter this replaces. Both services
/// now use the built-in generator, so both emit OpenAPI 3.1 and one client
/// generator can read both documents -- which is the whole point of the
/// generated client, and was not true while the API emitted 3.0.4 and the
/// consumer 3.1.1.
/// </summary>
public class TransactionHeaderTransformer : IOpenApiOperationTransformer
{
    public async Task TransformAsync(
        OpenApiOperation operation,
        OpenApiOperationTransformerContext context,
        CancellationToken cancellationToken)
    {
        operation.Parameters ??= [];

        // Read by RequestAuditMiddleware before model binding, which is why
        // they travel as headers rather than in a request body -- a GET has
        // no body to put them in, and the middleware runs too early to see
        // one anyway.
        operation.Parameters.Add(new OpenApiParameter
        {
            Name = TransactionContext.TransactionIdHeader,
            In = ParameterLocation.Header,
            Required = false,
            Description = "Caller-supplied transaction id (UUID), echoed back in the response meta. "
                        + "Generated by the server when omitted.",
            Schema = new OpenApiSchema { Type = JsonSchemaType.String, Format = "uuid" }
        });

        operation.Parameters.Add(new OpenApiParameter
        {
            Name = TransactionContext.ClientIdHeader,
            In = ParameterLocation.Header,
            Required = false,
            Description = "Calling application or channel, e.g. \"MobileApp\".",
            Schema = new OpenApiSchema { Type = JsonSchemaType.String }
        });

        await WrapResponsesInEnvelopeAsync(operation, context, cancellationToken);
    }

    /// <summary>
    /// MetaEnvelopeFilter wraps responses at runtime, which schema generation
    /// knows nothing about -- so without this the documented response shape
    /// would be the bare payload while the real one is { meta, data }. Anyone
    /// generating a client from this document would get it wrong, and would
    /// get it wrong silently: the types would compile and every field would
    /// be undefined.
    /// </summary>
    private static async Task WrapResponsesInEnvelopeAsync(
        OpenApiOperation operation,
        OpenApiOperationTransformerContext context,
        CancellationToken cancellationToken)
    {
        if (operation.Responses is null)
        {
            return;
        }

        // Generated once per operation rather than per response: the built-in
        // generator registers it in components and hands back a reference, so
        // the envelope costs one schema for the document rather than one per
        // response.
        var meta = await context.GetOrCreateSchemaAsync(
            typeof(ResponseMeta), cancellationToken: cancellationToken);

        foreach (var (status, response) in operation.Responses)
        {
            // 204 means there is no body, so there is no envelope to describe
            // either -- MetaEnvelopeFilter has nothing to wrap. The built-in
            // generator gives it a JSON content block anyway, which
            // Swashbuckle did not; left alone a generated client would wait
            // to parse a payload that never arrives.
            if (IsBodiless(status))
            {
                // Content is read-only on the interface; clearing the media
                // types leaves the response with just its description.
                response.Content?.Clear();
                continue;
            }

            if (response.Content is null)
            {
                continue;
            }

            foreach (var media in response.Content.Values)
            {
                media.Schema = new OpenApiSchema
                {
                    Type = JsonSchemaType.Object,
                    Properties = new Dictionary<string, IOpenApiSchema>
                    {
                        ["meta"] = meta,
                        ["data"] = media.Schema ?? new OpenApiSchema()
                    }
                };
            }
        }
    }

    /// <summary>
    /// Status codes RFC 9110 defines as carrying no body. 1xx and 304 are
    /// here for completeness; 204 is the one this API actually returns.
    /// </summary>
    private static bool IsBodiless(string status) =>
        status is "204" or "304" || status.StartsWith('1');
}
