// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NCBRS.Data;

#nullable disable

namespace NCBRS.Migrations
{
    [DbContext(typeof(NcbrsDbContext))]
    [Migration("20260914200438_IdempotencyRecords")]
    partial class IdempotencyRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("NCBRS.Models.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("AuditLogId");

                    b.HasIndex("TransactionId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("NCBRS.Models.BirthRecord", b =>
                {
                    b.Property<Guid>("BirthRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BirthOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BirthWeightGrams")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChildPersonId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FatherPersonId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GestationalAgeWeeks")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MotherPersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plurality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegisteredByRegistrarId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VitalEventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BirthRecordId");

                    b.HasIndex("Brn")
                        .IsUnique();

                    b.HasIndex("ChildPersonId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("FatherPersonId");

                    b.HasIndex("MotherPersonId");

                    b.HasIndex("RegisteredByRegistrarId");

                    b.ToTable("BirthRecords");
                });

            modelBuilder.Entity("NCBRS.Models.Certificate", b =>
                {
                    b.Property<Guid>("CertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BirthRecordId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssueDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("QrPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReprintCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SignatureHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CertificateId");

                    b.HasIndex("BirthRecordId")
                        .IsUnique();

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("NCBRS.Models.Facility", b =>
                {
                    b.Property<Guid>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("BrnBlockEnd")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BrnBlockNextAvailable")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BrnBlockStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectivityProfile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DistrictId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FacilityId");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("NCBRS.Models.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("IdempotencyRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LeaseExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("IdempotencyRecordId");

                    b.HasIndex("CompletedAtUtc");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("IdempotencyRecords");
                });

            modelBuilder.Entity("NCBRS.Models.MaternalOutcome", b =>
                {
                    b.Property<Guid>("BirthRecordId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeathDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IcdMmCauseCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecordedByRegistrarId")
                        .HasColumnType("TEXT");

                    b.HasKey("BirthRecordId");

                    b.HasIndex("RecordedByRegistrarId");

                    b.ToTable("MaternalOutcomes");
                });

            modelBuilder.Entity("NCBRS.Models.MaternalStatistics", b =>
                {
                    b.Property<Guid>("BirthRecordId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateOfLastLiveBirth")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FatherEducationLevelYears")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FatherOccupation")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("MedicalCareBeganDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotherEducationLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotherOccupation")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrenatalVisitCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriorFetalDeaths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriorLiveBirths")
                        .HasColumnType("INTEGER");

                    b.HasKey("BirthRecordId");

                    b.ToTable("MaternalStatistics");
                });

            modelBuilder.Entity("NCBRS.Models.NeonatalOutcome", b =>
                {
                    b.Property<Guid>("BirthRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContributingMaternalConditionCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeathDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IcdPmCauseCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IcdPmTiming")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecordedByRegistrarId")
                        .HasColumnType("TEXT");

                    b.HasKey("BirthRecordId");

                    b.HasIndex("RecordedByRegistrarId");

                    b.ToTable("NeonatalOutcomes");
                });

            modelBuilder.Entity("NCBRS.Models.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalIdRef")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("NCBRS.Models.Registrar", b =>
                {
                    b.Property<Guid>("RegistrarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RegistrarId");

                    b.HasIndex("FacilityId");

                    b.ToTable("Registrars");
                });

            modelBuilder.Entity("NCBRS.Models.RequestLog", b =>
                {
                    b.Property<Guid>("RequestLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TransactionIdGenerated")
                        .HasColumnType("INTEGER");

                    b.HasKey("RequestLogId");

                    b.HasIndex("TransactionId");

                    b.ToTable("RequestLogs");
                });

            modelBuilder.Entity("NCBRS.Models.SyncBatch", b =>
                {
                    b.Property<Guid>("SyncBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("SyncBatchId");

                    b.HasIndex("FacilityId");

                    b.ToTable("SyncBatches");
                });

            modelBuilder.Entity("NCBRS.Models.BirthRecord", b =>
                {
                    b.HasOne("NCBRS.Models.Person", "ChildPerson")
                        .WithMany()
                        .HasForeignKey("ChildPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NCBRS.Models.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NCBRS.Models.Person", "FatherPerson")
                        .WithMany()
                        .HasForeignKey("FatherPersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NCBRS.Models.Person", "MotherPerson")
                        .WithMany()
                        .HasForeignKey("MotherPersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NCBRS.Models.Registrar", "RegisteredByRegistrar")
                        .WithMany()
                        .HasForeignKey("RegisteredByRegistrarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildPerson");

                    b.Navigation("Facility");

                    b.Navigation("FatherPerson");

                    b.Navigation("MotherPerson");

                    b.Navigation("RegisteredByRegistrar");
                });

            modelBuilder.Entity("NCBRS.Models.Certificate", b =>
                {
                    b.HasOne("NCBRS.Models.BirthRecord", "BirthRecord")
                        .WithOne("Certificate")
                        .HasForeignKey("NCBRS.Models.Certificate", "BirthRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BirthRecord");
                });

            modelBuilder.Entity("NCBRS.Models.MaternalOutcome", b =>
                {
                    b.HasOne("NCBRS.Models.BirthRecord", "BirthRecord")
                        .WithOne("MaternalOutcome")
                        .HasForeignKey("NCBRS.Models.MaternalOutcome", "BirthRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NCBRS.Models.Registrar", "RecordedByRegistrar")
                        .WithMany()
                        .HasForeignKey("RecordedByRegistrarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BirthRecord");

                    b.Navigation("RecordedByRegistrar");
                });

            modelBuilder.Entity("NCBRS.Models.MaternalStatistics", b =>
                {
                    b.HasOne("NCBRS.Models.BirthRecord", "BirthRecord")
                        .WithOne("MaternalStatistics")
                        .HasForeignKey("NCBRS.Models.MaternalStatistics", "BirthRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BirthRecord");
                });

            modelBuilder.Entity("NCBRS.Models.NeonatalOutcome", b =>
                {
                    b.HasOne("NCBRS.Models.BirthRecord", "BirthRecord")
                        .WithOne("NeonatalOutcome")
                        .HasForeignKey("NCBRS.Models.NeonatalOutcome", "BirthRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NCBRS.Models.Registrar", "RecordedByRegistrar")
                        .WithMany()
                        .HasForeignKey("RecordedByRegistrarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BirthRecord");

                    b.Navigation("RecordedByRegistrar");
                });

            modelBuilder.Entity("NCBRS.Models.Registrar", b =>
                {
                    b.HasOne("NCBRS.Models.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("NCBRS.Models.SyncBatch", b =>
                {
                    b.HasOne("NCBRS.Models.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("NCBRS.Models.BirthRecord", b =>
                {
                    b.Navigation("Certificate");

                    b.Navigation("MaternalOutcome");

                    b.Navigation("MaternalStatistics");

                    b.Navigation("NeonatalOutcome");
                });
#pragma warning restore 612, 618
        }
    }
}
